### ISSUE TITLE
Cannot display Paywall

### ISSUE THREAD

**Issue by realcbnewham** [mirzemehdi/KMPRevenueCat#11]
I have set up RevenueCat and called the configure() which is successful.

When I try and call this (regardless of the shouldDisplayDismissButton being true or false) in my Composables screen:

Paywall(false, {}, null)

I get:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RCPaywallViewController initWithOffering:displayCloseButton:dismissRequestedHandler:]: unrecognized selector sent to instance 0x10e815600'
`

**Comment by mirzemehdi** [comment]
@realcbnewham 
1)which version of library you are using?
2)Did you include RevenueCat in Xcode with Swift Package Manager, and which version is that?

**Comment by realcbnewham** [comment]
Yes, both RevenueCat and RvenueCatUI have been added via SPM in XCode. The version shown in XCode is 4.41.1.

I'm using 0.2.0 of your library - the current one which you updated to fix the bug I last raised.

**Comment by mirzemehdi** [comment]
Currently last supported RevenueCat ios version is `4.39.0`. I'll bump it for new version of this library

**Comment by mirzemehdi** [comment]
This is fixed in `0.3.0` version
