### ISSUE TITLE
No ability to sync?

### ISSUE THREAD

**Issue by realcbnewham** [mirzemehdi/KMPRevenueCat#12]
It seems that there is no ability to sync subscriptions for users who have already taken out a subscription.

I'm updating my app, originally written in Swift/StoreKit, to KMP/RevenueCat and I will not be able to release the app until I have the ability to sync with existing subscriptions.

Could you please add the necessary call to the RevenueCat function to do this?

Thanks!

**Comment by mirzemehdi** [comment]
@realcbnewham What are necessary functions for that in RevenueCat?

**Comment by realcbnewham** [comment]
This is under "Client-side Migration" here:

https://www.revenuecat.com/docs/migrating-to-revenuecat/migrating-existing-subscriptions

**Comment by mirzemehdi** [comment]
Thank you, this will be added in version 0.3.0 version of library

**Comment by mirzemehdi** [comment]
This is implemented in `0.3.0` version
