### ISSUE TITLE
Paywall dismiss button does not work

### ISSUE THREAD

**Issue by realcbnewham** [mirzemehdi/KMPRevenueCat#14]
When using the Paywall composable on iOS I observe the following:

- The shouldDisplayDismissButton works correctly
- The onDismiss() lambda is called before/as the Paywall dialogue is displayed
- The onDismiss button (X at top right of dialogue on iOS) does nothing (that is, the lambda is never called)

The dialogue can be dismissed by pulling down on the dialogue, which I presume is how RevenueCat have designed it in case there is no dismiss button.

Not being familiar anymore with Swift (not done it in years) and how it interacts with Kotlin I asked GPT-4 about the KMPRevenueCat Paywall implementation and it told me:
"This completion block is executed right after the presentation animation completes, not when the dialog is dismissed."

which sounds right. But I expect you will see this :-)

Version 0.3.0

**Comment by mirzemehdi** [comment]
@realcbnewham fixed in version `0.3.1`
