### ISSUE TITLE
Listener methods do not work

### ISSUE THREAD

**Issue by msilimon** [mirzemehdi/KMPRevenueCat#19]
Hello!

I've noticed a problem, particularly on the iOS 17.2 emulator for iPhone 15. The onDismiss method is triggered if you press the cross within the first couple of seconds. After that, it doesn't work. Other methods either behave similarly or don't get triggered at all. Because of this, I can't retrieve the list during a purchase or properly handle the closing of the paywall. I checked the source code of your travel application and implemented everything exactly the same way.

Version 0.3.1 and 1.0.0

**Comment by msilimon** [comment]
Version 0.3.1 and 1.0.0

**Comment by mirzemehdi** [comment]
@msilimon now RevenueCat is supported offically for KMP: https://github.com/RevenueCat/purchases-kmp
