### ISSUE TITLE
Unable to use the library. co.touchlab:stately-common missing

### ISSUE THREAD

**Issue by realcbnewham** [mirzemehdi/KMPRevenueCat#7]
Although my project compiles up just fine and I have both RevenueCat Pods installed and have set up my gradle as given in your Blog post, I get the following gradle error as soon as I add the kmprevenuecat-purchases dependency to Common:

Could not find "co.touchlab:stately-common" in [/Users/cbnewham/Desktop/KeyholderKMP/shared, /Users/cbnewham/.konan/klib, /Users/cbnewham/.konan/kotlin-native-prebuilt-macos-x86_64-1.9.23/klib/common, /Users/cbnewham/.konan/kotlin-native-prebuilt-macos-x86_64-1.9.23/klib/platform/ios_arm64]

**Comment by mirzemehdi** [comment]
@realcbnewham Do you use kotlin version 1.9.23?

This library uses kotlin version 1.9.21. Maybe it is related to that I am not sure that.

**Comment by realcbnewham** [comment]
Thanks for the quick reply.  Yes, I am using the latest version of all libraries.

I did a Google search for that error - there is one thread in another github project and it may well be that you are correct and that it is due to using an older library.

I am looking forward to using your library - I signed up with RevenueCat today.

**Comment by mirzemehdi** [comment]
As a temporary solution please, check if it works with kotlin version 1.9.21. I'll bump kotlin version to 1.9.23 for next release

**Comment by realcbnewham** [comment]
Thanks, although my project is nearing completion and all I need is payments.  I have loads of libraries - not sure I could roll it back to that version. I'm also going away for a week. Anyway, I will have a look with a test project when I return, if you have not released another version by then. Thanks!

**Comment by mirzemehdi** [comment]
This is fixed in koin version `3.5.4` actually. Looks like it is not related kotlin version. As soon as koin 3.5.4 is in release, I'll bump koin version here.

Issue has also temporary solution.

Issue: https://github.com/InsertKoinIO/koin/issues/1785
PR: https://github.com/InsertKoinIO/koin/pull/1786

**Comment by mirzemehdi** [comment]
Should be fixed in library version `0.2.0` @realcbnewham
